spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:postgresql://localhost:5432/payment_system
    username: abdulhafiz
    password: 123
    driver-class-name: org.postgresql.Driver
  data:
    mongodb:
      uri: mongodb+srv://Jayxunbey:Ja2yx0un0be3y@cluster0.kgvfyje.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: payment_system
      auto-index-creation: true

  liquibase:
    change-log: classpath:db/liquabases/postgres/liqchangelog.xml

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  security:
    jwt:
      secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
      login-remember-me-expiration-time-minute: 21600
      login-without-remember-me-expiration-time-minute: 1440
      sending-sms-code-time-minute: 3

server:
  port: 8081

