spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: payment_system
    username: postgres
    password: 08211110476
    driver-class-name: org.postgresql.Driver
  data:
    mongodb:
      uri: mongodb+srv://Jayxunbey:Ja2yx0un0be3y@cluster0.kgvfyje.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: payment_system
      auto-index-creation: true

  liquibase:
    change-log: classpath:db/liquabases/postgres/liqchangelog.xml

  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: 8081

