spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:postgresql://localhost:5432/online_payment_system
    username: postgres
    password: Jayxunbey2003
    driver-class-name: org.postgresql.Driver


server:
  port: 8081

